name: Build and Deploy Go App

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get short SHA
        id: sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set environment variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENV=prod" >> $GITHUB_ENV
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
            echo "DEPLOY_PATH=prod" >> $GITHUB_ENV
          else
            echo "ENV=dev" >> $GITHUB_ENV
            echo "IMAGE_TAG=dev-${{ env.SHORT_SHA }}" >> $GITHUB_ENV
            echo "DEPLOY_PATH=dev" >> $GITHUB_ENV
          fi

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build Go binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app main.go

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t chicker94/rancher-ci-test:${{ env.IMAGE_TAG }} .
          docker push chicker94/rancher-ci-test:${{ env.IMAGE_TAG }}

  update-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CD repository
        uses: actions/checkout@v4
        with:
          repository: chicker94/fleet-cd-deployments
          ref: main
          ssh-key: ${{ secrets.CD_REPO_SSH_KEY }}
          path: cd-repo

      - name: Update Kubernetes manifest
        run: |
          sed -i "s|image: chicker94/rancher-ci-test:.*|image: chicker94/rancher-ci-test:${{ env.IMAGE_TAG }}|" cd-repo/${{ env.DEPLOY_PATH }}/deployment.yaml

      - name: Commit and push changes
        run: |
          cd cd-repo
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add ${{ env.DEPLOY_PATH }}/deployment.yaml
          git commit -m "Update image tag to ${{ env.IMAGE_TAG }}"
          git push
