name: Build and Deploy Go App

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_env.outputs.image_tag }}
      deploy_path: ${{ steps.set_env.outputs.deploy_path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get short SHA
        id: sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set environment variables
        id: set_env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENV=prod" >> $GITHUB_ENV
            echo "image_tag=${{ env.SHORT_SHA }}" >> $GITHUB_OUTPUT
            echo "deploy_path=prod" >> $GITHUB_OUTPUT
          else
            echo "ENV=dev" >> $GITHUB_ENV
            echo "image_tag=dev-${{ env.SHORT_SHA }}" >> $GITHUB_OUTPUT
            echo "deploy_path=dev" >> $GITHUB_OUTPUT
          fi

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build Go binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app main.go

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t chicker94/rancher-ci-test:${{ steps.set_env.outputs.image_tag }} .
          docker push chicker94/rancher-ci-test:${{ steps.set_env.outputs.image_tag }}

  update-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CD repository
        uses: actions/checkout@v4
        with:
          repository: chicker94/fleet-cd-deployments
          ssh-key: ${{ secrets.CD_REPO_SSH_KEY }}
          path: cd-repo
          
      - name: Determine branch and deployment path
        id: set-vars
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "BRANCH=main" >> $GITHUB_ENV
            echo "DEPLOY_PATH=prod/deployment.yaml" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "BRANCH=develop" >> $GITHUB_ENV
            echo "DEPLOY_PATH=dev/deployment.yaml" >> $GITHUB_ENV
          fi

      - name: Pull latest changes from the correct branch
        run: |
          cd cd-repo
          git checkout ${BRANCH}
          git pull origin ${BRANCH}

      - name: Update Kubernetes manifest
        run: |
          sed -i "s|image: chicker94/rancher-ci-test:.*|image: chicker94/rancher-ci-test:${{ needs.build-and-push.outputs.image_tag }}|" cd-repo/${DEPLOY_PATH}

      - name: Commit and push changes
        run: |
          cd cd-repo
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add ${DEPLOY_PATH}
          git commit -m "Update image tag to ${{ needs.build-and-push.outputs.image_tag }}"
          git push origin ${BRANCH}
